name: 'Client Deploy'

on:
  push:
    branches: [main]
    paths:
      - client/**
  workflow_dispatch:

jobs:
  client-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Client Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/BARAM/client
            git checkout -- .
            git pull
            pm2 stop baram_client
            yarn install
            yarn build
            pm2 restart baram_client
