name: Server CI

on:
  pull_request:
    branches: [main, dev]
    types: [opened, synchronize, reopened]
    paths:
      - server/**

jobs:
  server-ci:
    defaults:
      run:
        working-directory: server

    name: Server CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --passWithNoTests

      - name: Build
        run: yarn build
