name: 'Server Deploy'

on:
  push:
    branches: [main]
    paths:
      - server/**
  workflow_dispatch:

jobs:
  server-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Server Deploy
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/BARAM/server
            git checkout -- .
            git pull
            pm2 stop baram_server
            yarn install
            yarn build
            pm2 restart baram_server
